---
- name: get remote file contents
  command: "cat /etc/wireguard/ansible/{{ item.name}}/key.pub"
  register: user_key

- name: set clients vars
  ansible.builtin.set_fact:
    USER_KEY: "{{ user_key.stdout }}"

- name: set clients vars
  ansible.builtin.set_fact:
    dynamic_item: 
        name: "{{ item.name }}"
        ips: "{{ item.ips | join(', ')}}"
        key: "{{ USER_KEY }}"

- name: Add item to the list
  ansible.builtin.set_fact:
    TEMPLATE_USERS: "{{ TEMPLATE_USERS + [ dynamic_item ] }}"

- name: Debug the final list of dictionaries
  debug:
    var: TEMPLATE_USERS