---

- name: Check if the file exists
  stat:
    path: /etc/wireguard/ansible/{{ item.name }}/key.priv
  register: file_stat
  

- name: Generate Keyz
  shell:
    cmd: "wg genkey | tee key.priv | wg pubkey > client.pub"
    chdir: /etc/wireguard/ansible/{{ item.name }}
  when: not file_stat.stat.exists or file_stat.stat.size == 0
