---
# tasks file for wg_setup_server
- name: Creates config directory
  ansible.builtin.file:
    path: /etc/wireguard/ansible
    state: directory
    mode: "0755"

- name: Check if the file exists
  stat:
    path: /etc/wireguard/ansible/server.key
  register: file_stat

- name: Generate Keyz
  shell:
    cmd: "wg genkey | tee server.key | wg pubkey > server.pub"
    chdir: /etc/wireguard/ansible
  when: not file_stat.stat.exists or file_stat.stat.size == 0

- name: get remote file contents
  command: "cat /etc/wireguard/ansible/server.key"
  register: key

- name: set vars
  ansible.builtin.set_fact:
    PRIVATE_KEY: "{{ key.stdout }}"

- name: Template a file to /etc/file.conf
  ansible.builtin.template:
    src: server.conf.j2
    dest: /etc/wireguard/ansible/wg0.conf
    owner: root
    group: wheel
    mode: "0644"
