---
- name: "Playbook de Gestion d'instances Wireguard"
  hosts: bsd
  remote_user: nathan
  become: yes
  become_method: doas
  become_user: root
  gather_facts: true
  ignore_unreachable: true
  roles:
   - role: .